FROM --platform=$BUILDPLATFORM node:20.14.0-alpine3.20 as dependencies

ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM" > /log
WORKDIR /app
COPY package.json ./
RUN npm install

FROM node:20.14.0-alpine3.20 as builder
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
RUN npm run test

FROM node:20.14.0-alpine3.20 as prod-deps
WORKDIR /app
COPY package.json ./
RUN npm install --prod

FROM node:20.14.0-alpine3.20 as runner
WORKDIR /app
COPY --from=prod-deps /app/node_modules ./node_modules
COPY app.js ./
COPY tasks/ ./tasks
CMD [ "node", "app.js" ]
